name = "HSGPs"
uuid = "ad3833d4-b61d-4c64-b982-47e845742538"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"

[weakdeps]
WarmupHMC = "60658175-6863-4866-a322-ab51a11c0cfe"

[extensions]
HSGPsWarmupHMCext = "WarmupHMC"

[compat]
julia = "1"
